{{- if .Values.llm_loader.create -}}
{{ $model := .Values.llm_loader.model }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.llm_loader.jobName | default "llm-loader" }}
  labels:
    {{- include "psap-charts.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Values.llm_loader.containerName | default "llm-loader" }}
          image: {{ .Values.llm_loader.image | default "quay.io/kvalin/llm-loader:latest" }}
          {{ if eq .Values.llm_loader.source "huggingface" -}}
          tty: true
          {{- if or .Values.hf_token.create .Values.hf_token.secretName }}
          envFrom:
          - secretRef:
              name: {{ .Values.hf_token.secretName | default "hf-token" }}
          {{- end }}
          {{- end }}
          env:
           - name: HOME
             value: {{ .Values.llm_loader.outputDir | default (printf "/models/%s" $model) }}
          args:
            - --output_dir={{ .Values.llm_loader.outputDir | default (printf "/models/%s" $model) }}
            - {{ .Values.llm_loader.source }}
            {{ if eq .Values.llm_loader.source "huggingface" -}}
            - --repo_id={{ $model }}
            {{- end }}
          volumeMounts:
          - name: models
            mountPath: {{ .Values.llm_loader.outputDir | default "/models" }}
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: {{ .Values.llm_loader.pvcName | default "llm-loader-pvc" }}
{{- end -}}